language: elixir

elixir:
  - 1.6.1

otp_release:
  - 20.0

env:
  - MIX_ENV=test


script:
  - make test
  - make dialyzer-ci
  - make coveralls-travis

cache:
  directories:
    - ~/.mix
    - ~/.hex
